<a href="https://colab.research.google.com/github/govindyadav1132-byte/147_Govind_TYCS/blob/main/AI_ML_BootCamp_Day1_n_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(5 == 5)
print(6 != 7)
print(9 > 6)
print(5 < 3)
print(6 >= 7)
print(8 <= 9 )

True
True
True
False
False
True

In [ ]:
x= 5
x += 5
print(x)
x -=4
print(x)
x *=2
print(x)

12

In [ ]:
a= [2,4,6,8,10]
print(2 in a)
print(7 not in a)

True
True

In [ ]:
a = [1,2]
b = a
c = [1,2]

print(a is b)
print(a is c)
print(a == c)

True
False
True

In [ ]:
a,b=7,8
print( a & b)
print( a | b)
print(a ^ b)
print(a << b)
print(a >> b)

0
15
15
1792
0

In [ ]:
a = "Run Python"
print(a[0:1])
print(a[::-1])
print(a[3:7])

R
nohtyP nuR
 Pyt

In [ ]:
a="Dinku"
b="Chand"
print(a + " " + b)
print(a * 3)

Dinku Chand
DinkuDinkuDinku

In [ ]:
a= "World at the end"
print(a.upper())
print(a.lower())
print(a.strip())
print(a.replace("at","in"))
print(a.split(" "))
print(a.find("end"))

WORLD AT THE END
world at the end
World at the end
World in the end
['World', 'at', 'the', 'end']
13

In [ ]:
print(f"1.{a} 2.{a}")

1.World at the end 2.World at the end

In [ ]:
name=str(input("Enter Your Name :"))
age=int(input("Enter Your Age :"))
if age >= 18:
  print("Adult")
else:
  print("Minor")

Enter Your Name :Son Dinku
Enter Your Age :23
Adult

In [ ]:
age=12
if age < 18:
  print(f"Wait for {18-age} Years.")
elif age == 18:
  print("You Can Drive")
else:
  print("No Obj")

Wait for 6 Years.

In [ ]:
num = 3
if num > 0:
  if num%2==0 :
    print("Even")
  else:
    print("Odd")

Odd

In [ ]:
for i in range(5,9):
  print(i)

5
6
7
8

In [ ]:
for i in range(3):
  for j in range(2):
    print(f"i={i},j={j}")
  print()

i=0,j=0
i=0,j=1

i=1,j=0
i=1,j=1

i=2,j=0
i=2,j=1

In [ ]:
count = 0
while count <= 5:
  print(count)
  count+=1

0
1
2
3
4
5

In [ ]:
for i in range(10):
  if i == 5:
    break
  print(i)

5

In [ ]:
f=["apple","banana","cherry"]
f.append("orange")
f.insert(1,"kiwi")
print(f)

f.remove("banana")
print(f)
f.pop()
print(f)

['apple', 'kiwi', 'banana', 'cherry', 'orange']
['apple', 'kiwi', 'cherry', 'orange']
['apple', 'kiwi', 'cherry']

In [ ]:
a=[7,1,5,4,3]
a.sort()
print(a)

[1, 3, 4, 5, 7]

In [ ]:
b=[3,4,5,6,3,8]
print(a + b)

[1, 3, 4, 5, 7, 3, 4, 5, 6, 3, 8]

In [ ]:
s={1,2,3,2,1,4,2,3,1}
s.add(5)
s.remove(2)
print(s)

{1, 3, 4, 5}

In [ ]:
a={1,2,3,4,5}
b={3,4,5,6,7}
print(a.union(b))
print(a.intersection(b))

{1, 2, 3, 4, 5, 6, 7}
{3, 4, 5}

In [ ]:
def greet(name,greeting="Hello"):

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

sns.set_theme(style="whitegrid")

In [9]:
tempratures = pd.Series(
    [30.5,28.2,32.1,27.8,29.9],
    index=["Mon","Tue","Wed","Thu","Fri"],
    name="temprature_c"
)

print(tempratures)
print("\n Type :",type(tempratures))
print("Access by label 'wed':",tempratures["Wed"]) `+
print("Access by position 0 :",tempratures.iloc[0])

Mon    30.5
Tue    28.2
Wed    32.1
Thu    27.8
Fri    29.9
Name: temprature_c, dtype: float64

 Type : <class 'pandas.core.series.Series'>
Access by label 'wed': 32.1
Access by position 0 : 30.5

In [13]:
data ={
    "city":["Mumbai","Delhi","Bangalore","Chennai","Kolkata"],
    "temperature_c": [30.5,28.2,32.1,27.8,29.9],
    "humidity_pct": [78,45,65,80,82],
    "is_coastal":[True,True,False,False,True]
    }

df= pd.DataFrame(data)
df

        city  temperature_c  humidity_pct  is_coastal
0     Mumbai           30.5            78        True
1      Delhi           28.2            45        True
2  Bangalore           32.1            65       False
3    Chennai           27.8            80       False
4    Kolkata           29.9            82        True

In [14]:
print("Shape (rows , cols):", df.shape)
print("\nColumn names :",list(df.columns))
print(df.dtypes)
print("\nQuick Summary stats :")
df.describe()

Shape (rows , cols): (5, 4)

Column names : ['city', 'temperature_c', 'humidity_pct', 'is_coastal']
city              object
temperature_c    float64
humidity_pct       int64
is_coastal          bool
dtype: object

Quick Summary stats :

       temperature_c  humidity_pct
count       5.000000      5.000000
mean       29.700000     70.000000
std         1.753568     15.475788
min        27.800000     45.000000
25%        28.200000     65.000000
50%        29.900000     78.000000
75%        30.500000     80.000000
max        32.100000     82.000000

In [18]:
print("Row with label 2 (via .loc):")
print(df.loc[2])
print("\n")
print("\n")

print("n First 2 rows, first 2 col;umns (via .iloc) :")
print(df.iloc[0:2 , 0:2])
print("\n")
print("\n")

print("\n Just the city column(return a Series) :")
print(df["city"])

print("\nSpecific cell: city of rows 3 (via .loc) :")
print(df.loc[3, 'city'])

Row with label 2 (via .loc):
city             Bangalore
temperature_c         32.1
humidity_pct            65
is_coastal           False
Name: 2, dtype: object




n First 2 rows, first 2 col;umns (via .iloc) :
     city  temperature_c
0  Mumbai           30.5
1   Delhi           28.2





 Just the city column(return a Series) :
0       Mumbai
1        Delhi
2    Bangalore
3      Chennai
4      Kolkata
Name: city, dtype: object

Specific cell: city of rows 3 (via .loc) :
Chennai

In [20]:
hot= df[df["temperature_c"] > 33 ]
print(" Cities hotter than 33 C")

print(hot)

coastal_and_humid = df[(df["is_coastal"] == True) & (df["humidity_pct"] > 75)]
print("\n Coastal cities with hmidity > 75% :")
print(coastal_and_humid)

 Cities hotter than 33 C
Empty DataFrame
Columns: [city, temperature_c, humidity_pct, is_coastal]
Index: []

 Coastal cities with hmidity > 75% :
      city  temperature_c  humidity_pct  is_coastal
0   Mumbai           30.5            78        True
4  Kolkata           29.9            82        True

In [ ]:
+